#!/bin/sh
# Imports real ECU identification replies from commaai/opendbc (MIT) as sim test data (issue #15).
# opendbc keeps each car's firmware versions in opendbc/car/<make>/fingerprints.py, as the reply to
# a multi-DID ReadDataByIdentifier without its 0x62 service ID.
#
#   scripts/import-opendbc.sh <make> <commit> <out.toml> <CAR>...
#   scripts/import-opendbc.sh volkswagen 229dc7062d8986b4f954c7c97875b4ffd0044d12 \
#       crates/obdcracker-sim/fixtures/opendbc-vag.toml AUDI_Q5_MK1 PORSCHE_MACAN_MK1
#
# Only engine and transmission entries are imported. Add the commit to THIRD_PARTY.md.
set -e
[ $# -ge 4 ] || { sed -n 2,10p "$0" >&2; exit 2; }
make=$1 commit=$2 out=$3
shift 3
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT
curl -fsSL "https://raw.githubusercontent.com/commaai/opendbc/$commit/opendbc/car/$make/fingerprints.py" \
	-o "$tmp/fingerprints.py"
# -I: the downloaded file is only read, never imported.
python3 -I - "$tmp/fingerprints.py" "$make" "$commit" "$@" >"$out" <<'PY'
import ast, re, sys

path, make, commit, cars = sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4:]
car = key = None
entries = []
for line in open(path):
    if m := re.match(r"  CAR\.(\w+): \{", line):
        car = m.group(1)
    elif m := re.match(r"    \(Ecu\.(\w+), (0x[0-9a-f]+), None\): \[", line):
        key = (m.group(1), int(m.group(2), 16))
    elif (m := re.match(r"      (b'.*'),$", line)) and car in cars and key[0] in ("engine", "transmission"):
        entries.append((car, key[0], key[1], ast.literal_eval(m.group(1))))
missing = set(cars) - {e[0] for e in entries}
if missing:
    sys.exit(f"no engine or transmission entries for {', '.join(sorted(missing))}")

print(f"# Generated by scripts/import-opendbc.sh from commaai/opendbc (MIT), commit {commit},")
print(f"# opendbc/car/{make}/fingerprints.py. Each `data` is a module's reply to a multi-DID")
print("# ReadDataByIdentifier, without the 0x62 service ID. Don't edit; re-run the script.")
for car, ecu, request_id, data in entries:
    print()
    print("[[reply]]")
    print(f'car = "{car}"')
    print(f'ecu = "{ecu}"')
    print(f"request_id = 0x{request_id:03X}")
    print(f'data = "{data.hex(" ").upper()}"')
PY
